version: '3'

volumes:
  consul-server-data:
    driver: local
  consul-server-config:
    driver: local

services:

  consul-server-bootstrap:
    image: consul:latest
    container_name: consul-server-bootstrap
    hostname: "consul-server"
    environment:
      CONSUL_CLIENT_INTERFACE: "eth0"
      CONSUL_BIND_INTERFACE: "eth0"
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "53:8600/udp"
    volumes:
      - consul-server-data:/consul/data
      - consul-server-config:/consul/config
    command: "agent -server -ui -client 0.0.0.0 -bootstrap-expect=1 -advertise 172.16.1.10 -data-dir=/consul/data
    -config-dir=/consul/config"
    restart: on-failure
    network_mode: "bridge"

  registrator:
    image: gliderlabs/registrator:latest
    hostname: "registrator"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: "-resync 120 -retry-attempts -1 -retry-interval 12000 consul://172.16.1.10:8500"
    depends_on:
      - consul-server-bootstrap
    network_mode: "bridge"
